name: Build LaTeX Resume

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Compile LaTeX
      uses: xu-cheng/latex-action@v3
      with:
        root_file: resume.tex  # Your main .tex file
        args: -pdf -file-line-error -halt-on-error
    - name: Rename PDF
      run: |
        mv resume.pdf Yu_Hang_Resume.pdf
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: Yu_Hang_Resume
        path: Yu_Hang_Resume.pdf
    - name: Commit PDF
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Update resume.pdf
        file_pattern: Yu_Hang_Resume.pdf
